# https://www.mkdocs.org/user-guide/configuration
# https://github.com/squidfunk/mkdocs-material/blob/d51279ae72ffed88e4060b738ae4903b43d001ac/mkdocs.yml

theme:
  name: material

  palette:
  - media: "(prefers-color-scheme: light)"
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
    primary: green
    accent: light green
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: red
    accent: red
    toggle:
      icon: material/weather-night
      name: Switch to light mode

  features:
  - navigation.instant
  - navigation.tracking
  # - navigation.expand
  - toc.integrate
  - navigation.top
  - content.code.annotate

site_name: Docs
site_url: https://docs.fuzzymonkey.co

repo_url: https://github.com/FuzzyMonkeyCo/docs.fuzzymonkey.co
edit_uri: blob/main/docs/

plugins:
- search
- minify:
    minify_html: true
# - markdownextradata: {}
#https://github.com/rosscdh/mkdocs-markdownextradata-plugin
# extra:
#   monkey_version: MONKEY_VERSION # TODO: rewrite from github's releases/latest

markdown_extensions:
- footnotes
- meta
- toc:
    permalink: true

- pymdownx.arithmatex:
    generic: true
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
# - pymdownx.magiclink:
#     repo_url_shorthand: true
#     user: squidfunk
#     repo: mkdocs-material
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid-experimental
        format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde

nav:
- Home:
  - Vision: vision.md
  - Getting started: getting-started.md
  - Glossary: glossary.md
- Installing monkey:
  - Overview: installation-overview.md
  - macOS: installation-macos.md
  - Ubuntu: installation-ubuntu.md
  - Windows: installation-windows.md
  - with Docker: installation-docker.md
  - Compiling from source: installation-source.md
  - Updating monkey: updating-monkey.md
- Setting up your environment:
  - Command-line completion: cli-completion.md
  - Integrating with IDEs: ide-integration.md
- Tutorials:
  - demo1: tutorial-demo1.md
  - Hot express-js app with npm and github action: tutorial-demo2.md
  - Elixir openapi app REST with gitlab CI: tutorial-demo3.md
  - Go using Goa: tutorial-demo4.md
- Understanding:
  - Core concepts: concepts-core.md
  - Hermeticity: concepts-hermeticity.md
  - The Starlark language: starlark.md
  - assert.that(..): assert_that.md
  - Command-line reference: cli-reference.md
- Releases:
  - Backwards compatibility: backwards-compatibility.md

# - Getting started:
#   - Installation: install.md
#   - Your first tests: starting.md
# - Command-line reference:
#   - Usage: usage.md
#   - monkey init: monkey/init.md
#   # - monkey fuzz: monkey/fuzz.md
#   # - monkey lint: monkey/lint.md
#   # - monkey fmt: monkey/fmt.md
#   # - monkey schema: monkey/schema.md
#   # - monkey exec: monkey/exec.md
#   # - monkey env: monkey/env.md
#   # - monkey logs: monkey/logs.md
#   # - monkey pastseed: monkey/pastseed.md
#   # - monkey update: monkey/update.md
# - Languages:
#   - Starlark:
#     - The language: starlark/index.md
#     - Tools:
#       - OpenAPIv3: starlark/modeling-openapiv3.md
#       - Check: starlark/builtin-check.md
#       - Env: starlark/builtin-env.md
#       - assert.that(..): starlark/assert_that.md

# - Blog:
#   - blog/index.md
#   - 2021:
#     - blog/2021/excluding-content-from-search.md
#     - blog/2021/search-better-faster-smaller.md
