version: 0

documentation:
  kind: openapi_v2
  file: priv/openapi2v1.yml
  host: '{{ env "my_host" }}'
  port: 6773


# Environment variables created / modified in start / stop are accessible in stop / reset / start.

# Documentation's 'host' & 'port' can be resolved from the environment:
# The mustache syntax:  {{ env "a_var" }}
# Gets resolved by `monkey` into the result of `echo -n $a_var`.
# Note that unset variables or empty values result in a runtime error.

start:
  - my_host=127.0.0.1  # This variable is set only once: here.
  - |
    until RELX_REPLACE_OS_VARS=true ./_build/prod/rel/sample/bin/sample status 1>&2; do
      RELX_REPLACE_OS_VARS=true ./_build/prod/rel/sample/bin/sample start 1>&2
      sleep 1
    done

reset:
  - "[[ 204 = $(curl --silent --output /dev/null --write-out '%{http_code}' -X DELETE http://$my_host:6773/api/1/items) ]]"

stop:
  - RELX_REPLACE_OS_VARS=true ./_build/prod/rel/sample/bin/sample stop 1>&2
  - echo Stopped $my_host
