# Identifies FuzzyMonkeyCo's configuration format
version: 0

# Data describing Web APIs
documentation:
  kind: openapi_v2
  # Note: references to schemas in `file` are resolved relative to file's location.
  file: priv/openapi2v1.yml
  host: localhost
  port: 6773


# Note: commands are executed in shells sharing the same environment variables,
# with `set -e` and `set -o pipefail` flags on.

# The following get executed once per test
#   so have these commands complete as fast as possible.
# Also, make sure that each test starts from a clean slate
#   otherwise results will be unreliable.

start:
  - |
    until RELX_REPLACE_OS_VARS=true ./_build/prod/rel/sample/bin/sample status 1>&2; do
      RELX_REPLACE_OS_VARS=true ./_build/prod/rel/sample/bin/sample start 1>&2
      sleep 1
    done

stop:
  - RELX_REPLACE_OS_VARS=true ./_build/prod/rel/sample/bin/sample stop 1>&2
