sudo: false
language: erlang
otp_release: 22.0

before_script:
- |
  curl -# --fail --output /usr/local/bin/rebar3 https://s3.amazonaws.com/rebar3/rebar3
  chmod +x /usr/local/bin/rebar3
  rebar3 --version
- monkey update || curl -#fL https://git.io/FuzzyMonkey | BINDIR=/usr/local/bin sh
- monkey version
script:
- ./check.sh
- |
  if command -v docker >/dev/null 2>&1; then
    [[ 0 -eq $(docker ps -q | wc -l) ]]
  else
    ! curl --output /dev/null --silent --fail --head http://localhost:6773/api/1/items
  fi
after_script:
- set +e

matrix:
  include:
  - env: STAR=fuzzymonkey__start_reset_stop_docker.star
    services: docker
  - env: STAR=fuzzymonkey__start_reset_stop.star
  - env: STAR=fuzzymonkey__start_reset_stop_json.star
  - env: STAR=fuzzymonkey__start_reset_stop_failing_script.star
  - env: STAR=fuzzymonkey.star
  - env: STAR=fuzzymonkey__env.star
  - env: STAR=fuzzymonkey__doc_typo.star
  - env: STAR=fuzzymonkey__doc_typo_json.star

env:
  global:
  # secure: FUZZYMONKEY_API_KEY=...
  - secure: KxfD/V81Gn8/B21wNKMQxd27N+75/AjlINfjrA2Tv9wDUPXDYB/tA3gbqGL2yPnKXKHm7x5LsOR4+WMppDofIeY4rAYdaypJPkLgw2p3oKK+oSy4j5fz2xt/PsY2djsPm3w5xUcmfNoX4HhftXzGQSA/8MbqF1jcJCiEOu/8ZNjBCT/HfeGzD7gcYzNSkj/bWsOq00gtYD2aVlYkiJrXdYgzoeTEOvfZ4zJmKW770Jm9YZNFdmEmMuj8H4wqVDvOC9Y89l2GxhSdgcxw6hvRyhKKtz86p1O8bpkhF7rlZJBi/+yGOVc9ZDoHcVSVlmiP26I5Mnlm5J7ZuXj3lCzI7LP/i3TqzwQlEwpEzIj/iLr0X3kTBGxbP11Z4ykZFGiddT2SiFeycn2vSCjyinZOG49ZP8jDwgOJToeT/leut2dzKguGDr+IR0VtIxHTV30JR5kHWparsdgMSELUXbRHvIArVEkeKsQahAUYhU/LHKfxUOWqCZFD7/+TeFDLTWNsdNLl98luItOnRBSHlvbIiJb1xyJCOJCjcYU8X3ScGpqIPcMag0xG137Xd0zgrhCa2hwhTBbF/jpGzWvLtV2vd8Ys8UxaHv5FTlAgUBcWTqXTDqHHGjCfA4+VcSrCX8A/0kk3hsy03O8zBHSAkrREsMgPDYseYUNCMAvf3TnfT3M=

notifications:
  email:
    on_success: never
